include ':capacitor-android'
if (new File('../node_modules/@capacitor/android/capacitor').exists()) {
    project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
} else {
    def f = fileTree('../node_modules').matching { include '**/@capacitor/android/capacitor/build.gradle' }.files
    if (!f.empty) {
        project(':capacitor-android').projectDir = f.first().parentFile
    } else {
        project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
    }
}
